'/Script/ShooterGame.Object':
- '/Script/ShooterGame.Actor':
    - '/Script/ShooterGame.DroppedItem': # Done
        - '/Script/ShooterGame.DroppedItemEgg'
        - '/Script/ShooterGame.DroppedItemLowQuality':
            - '/Script/ShooterGame.DroppedItemTorch'
    - '/Script/ShooterGame.Info': # Done
        - '/Script/ShooterGame.DayCycleManager'
        - '/Script/ShooterGame.GameMode':
            - '/Script/ShooterGame.LocalSpawnGameMode'
            - '/Script/ShooterGame.ShooterGame_Menu'
            - '/Script/ShooterGame.ShooterGameMode':
                - '/Script/ShooterGame.CustomGameMode'
        - '/Script/ShooterGame.GameState':
            - '/Script/ShooterGame.ShooterGameState':
                - '/Script/ShooterGame.BattleGameState'
                - '/Script/ShooterGame.CustomGameState'
        - '/Script/ShooterGame.MatineeActorManager'
        - '/Script/ShooterGame.NPCZoneManager'
        - '/Script/ShooterGame.PlayerState':
            - '/Script/ShooterGame.ShooterPlayerState'
        - '/Script/ShooterGame.PrimalStructurePlacer'
        - '/Script/ShooterGame.SkyLight'
    - '/Script/ShooterGame.PrimalTargetableActor': # Done
        - '/Script/ShooterGame.PrimalStructure':
            - '/Script/ShooterGame.PrimalStructureBearTrap'
            - '/Script/ShooterGame.PrimalStructureDoor':
                - '/Script/ShooterGame.PrimalStructureSkeletalDoor'
            - '/Script/ShooterGame.PrimalStructureElevatorPlatform'
            - '/Script/ShooterGame.PrimalStructureExplosive':
                - '/Script/ShooterGame.PrimalStructureExplosiveTransGPS'
                - '/Script/ShooterGame.PrimalStructureTripwire'
            - '/Script/ShooterGame.PrimalStructureItemContainer':
                - '/Script/ShooterGame.PrimalStructureElevatorTrack'
                - '/Script/ShooterGame.PrimalStructureItemContainer_CropPlot':
                    - '/Script/ShooterGame.PrimalStructureItemContainer_CropPlot_VisualItems'
                - '/Script/ShooterGame.PrimalStructureItemContainer_SupplyCrate':
                    - '/Script/ShooterGame.PrimalStructureItemContainer_HordeCrate'
                - '/Script/ShooterGame.PrimalStructureItemContainer_VisualItems'
                - '/Script/ShooterGame.PrimalStructureKeypad'
                - '/Script/ShooterGame.PrimalStructureMovingContainer'
                - '/Script/ShooterGame.PrimalStructureSeating':
                    - '/Script/ShooterGame.PrimalStructureBed'
                    - '/Script/ShooterGame.PrimalStructureSeatingMusic'
                    - '/Script/ShooterGame.PrimalStructureTurretBallista'
                - '/Script/ShooterGame.PrimalStructureTurret':
                    - '/Script/ShooterGame.PrimalStructureTurretPlant'
                - '/Script/ShooterGame.PrimalStructureUnderwaterBase'
            - '/Script/ShooterGame.PrimalStructureLadder':
                - '/Script/ShooterGame.PrimalStructurePortableLadder'
            - '/Script/ShooterGame.PrimalStructureSeaMine'
            - '/Script/ShooterGame.PrimalStructureSign'
            - '/Script/ShooterGame.PrimalStructureWaterPipe'
    - '/Script/ShooterGame.ShooterProjectile': # Done
        - '/Script/ShooterGame.PrimalProjectileArrow':
            - '/Script/ShooterGame.PrimalProjectileBoomerang'
            - '/Script/ShooterGame.PrimalProjectileNetGun'
        - '/Script/ShooterGame.PrimalProjectileDilo'
        - '/Script/ShooterGame.PrimalProjectileFlare'
        - '/Script/ShooterGame.PrimalProjectileGrapplingHook'
        - '/Script/ShooterGame.PrimalProjectileSpiderAcid'
        - '/Script/ShooterGame.ShooterProjectile_Swarm'
    - '/Script/ShooterGame.ShooterWeapon': # Done
        - '/Script/ShooterGame.ShooterWeapon_ChainSaw'
        - '/Script/ShooterGame.ShooterWeapon_FlameThrower'
        - '/Script/ShooterGame.ShooterWeapon_Instant':
            - '/Script/ShooterGame.ShooterWeapon_InstantPenetrating'
        - '/Script/ShooterGame.ShooterWeapon_Melee':
            - '/Script/ShooterGame.PrimalWeaponElectronicBinoculars'
            - '/Script/ShooterGame.PrimalWeaponGPS'
            - '/Script/ShooterGame.ShooterWeapon_Climb'
            - '/Script/ShooterGame.ShooterWeapon_Whip'
        - '/Script/ShooterGame.ShooterWeapon_Placer':
            - '/Script/ShooterGame.ShooterWeapon_PlacerTransGPS'
        - '/Script/ShooterGame.ShooterWeapon_Projectile':
            - '/Script/ShooterGame.PrimalWeaponBow':
                - '/Script/ShooterGame.PrimalWeaponBoomerang'
            - '/Script/ShooterGame.PrimalWeaponGrapplingHook'
            - '/Script/ShooterGame.PrimalWeaponGrenade'
- '/Script/ShooterGame.ActorComponent':
    - '/Script/ShooterGame.PrimalInventoryComponent':
        - '/Script/ShooterGame.PrimalInventoryComponent_Static'
- '/Script/ShooterGame.PrimalItem':
    - '/Script/ShooterGame.PrimalItem_Dye'
    - '/Script/ShooterGame.PrimalItem_Radio'
- '/Script/ShooterGame.PrimalStructureSettings'

# Unknown, need placing
- '/Engine/Transient.REINST_ElementWall_Horde_C_8303'
- '/Script/AIModule.BTDecorator_BlueprintBase'
- '/Script/AIModule.BTService_BlueprintBase'
- '/Script/AIModule.BTTask_BlueprintBase'
- '/Script/CoreUObject.Interface'
- '/Script/CoreUObject.Object'
- '/Script/Engine.Actor'
- '/Script/Engine.AnimInstance'
- '/Script/Engine.AnimNotify'
- '/Script/Engine.AnimNotifyState'
- '/Script/Engine.BlueprintFunctionLibrary'
- '/Script/Engine.BoxReflectionCapture'
- '/Script/Engine.CameraShake'
- '/Script/Engine.Character'
- '/Script/Engine.DirectionalLight'
- '/Script/Engine.Emitter'
- '/Script/Engine.GroundClutterLayerActor'
- '/Script/Engine.HierarchicalInstancedStaticMeshActor'
- '/Script/Engine.LevelScriptActor'
- '/Script/Engine.MatineeActor'
- '/Script/Engine.Note'
- '/Script/Engine.PointLight'
- '/Script/Engine.PostProcessVolume'
- '/Script/Engine.SkeletalMeshActor'
- '/Script/Engine.SkeletalMeshComponent'
- '/Script/Engine.SkyLight'
- '/Script/Engine.SphereReflectionCapture'
- '/Script/Engine.SplineActor'
- '/Script/Engine.SpotLight'
- '/Script/Engine.StaticMeshActor'
- '/Script/Engine.TargetPoint'
- '/Script/Engine.VehicleAnimInstance'
- '/Script/Engine.VehicleWheel'
- '/Script/ShooterGame.BiomeZoneSettings'
- '/Script/ShooterGame.CharacterViewPanelWidget'
- '/Script/ShooterGame.ContextMenu_InventorySort'
- '/Script/ShooterGame.ContextMenu_PrimalItem'
- '/Script/ShooterGame.ContextMenu'
- '/Script/ShooterGame.ContextMenuItem_Sort'
- '/Script/ShooterGame.ContextMenuItem_Spinner'
- '/Script/ShooterGame.ContextMenuItem'
- '/Script/ShooterGame.DataListEntryButton_DyeResources'
- '/Script/ShooterGame.DataListEntryButton_HostSession'
- '/Script/ShooterGame.DataListEntryButton_ListSession'
- '/Script/ShooterGame.DataListEntryButton_MainMenu'
- '/Script/ShooterGame.DataListEntryEngramList'
- '/Script/ShooterGame.DataListEntryWidget'
- '/Script/ShooterGame.DestroyedMeshActor'
- '/Script/ShooterGame.DinoAncestryEntryWidget'
- '/Script/ShooterGame.DinoListButtonWidget'
- '/Script/ShooterGame.DinoListItemTooltip'
- '/Script/ShooterGame.DyeRegionButtonWidget'
- '/Script/ShooterGame.FadingDestructibleActor'
- '/Script/ShooterGame.FogOfWar'
- '/Script/ShooterGame.GamepadButtonLegendWidget'
- '/Script/ShooterGame.HordeCrateManager'
- '/Script/ShooterGame.HUDCustomStatusWidget'
- '/Script/ShooterGame.HUDElementBarWidget'
- '/Script/ShooterGame.HUDStatusBarsWidget'
- '/Script/ShooterGame.InventoryArkCreaturesPanel'
- '/Script/ShooterGame.InventoryDinoAncestryPanel'
- '/Script/ShooterGame.InventoryPanelWidget'
- '/Script/ShooterGame.InventoryStatsPanel'
- '/Script/ShooterGame.NPCSpawnEntriesContainer'
- '/Script/ShooterGame.PlayerHUDUI'
- '/Script/ShooterGame.PrimalAIState'
- '/Script/ShooterGame.PrimalAIStateBPBase'
- '/Script/ShooterGame.PrimalAIStateDinoFlyerGrab'
- '/Script/ShooterGame.PrimalAIStateDinoGrabAndReleaseState'
- '/Script/ShooterGame.PrimalAIStateDinoMeleeState'
- '/Script/ShooterGame.PrimalAIStateDinoRangedState'
- '/Script/ShooterGame.PrimalAIStateDinoSpiderMinions'
- '/Script/ShooterGame.PrimalAIStateDinoSpiderRangedAcidState'
- '/Script/ShooterGame.PrimalAIStateDinoSpiderRangedWebState'
- '/Script/ShooterGame.PrimalAIStateDinoSpineyLizardTailRangeState'
- '/Script/ShooterGame.PrimalBuff'
- '/Script/ShooterGame.PrimalBuffPersistentData'
- '/Script/ShooterGame.PrimalClimbingSettings'
- '/Script/ShooterGame.PrimalColorSet'
- '/Script/ShooterGame.PrimalDinoAIController'
- '/Script/ShooterGame.PrimalDinoCharacter'
- '/Script/ShooterGame.PrimalDinoEntry'
- '/Script/ShooterGame.PrimalDinoSettings'
- '/Script/ShooterGame.PrimalDinoStatusComponent'
- '/Script/ShooterGame.PrimalDinoToolTipWidget'
- '/Script/ShooterGame.PrimalEmitterSpawnable'
- '/Script/ShooterGame.PrimalEngramEntry'
- '/Script/ShooterGame.PrimalGameData'
- '/Script/ShooterGame.PrimalGlobals'
- '/Script/ShooterGame.PrimalHarvestingComponent'
- '/Script/ShooterGame.PrimalItemInventoryToolTipWidget'
- '/Script/ShooterGame.PrimalItemToolTipWidget'
- '/Script/ShooterGame.PrimalPlayerData'
- '/Script/ShooterGame.PrimalPlayerStatusComponent'
- '/Script/ShooterGame.PrimalRaft'
- '/Script/ShooterGame.PrimalStructureToolTipWidget'
- '/Script/ShooterGame.PrimalSupplyCrateItemSet'
- '/Script/ShooterGame.PrimalSupplyCrateItemSets'
- '/Script/ShooterGame.PrimalUI'
- '/Script/ShooterGame.PrimalWheeledVehicleCharacter'
- '/Script/ShooterGame.RadialSelectorHUD_Inventory'
- '/Script/ShooterGame.RadialSelectorHUD_MultiUse'
- '/Script/ShooterGame.RadialSelectorHUD_PlayerAction'
- '/Script/ShooterGame.SaveGameActorTickable'
- '/Script/ShooterGame.ShooterCharacter'
- '/Script/ShooterGame.ShooterDamageType'
- '/Script/ShooterGame.ShooterHUD'
- '/Script/ShooterGame.ShooterImpactEffect'
- '/Script/ShooterGame.ShooterPlayerCameraManager'
- '/Script/ShooterGame.ShooterPlayerController'
- '/Script/ShooterGame.StatsPanelWidget_Character'
- '/Script/ShooterGame.StatsPanelWidget_Obelisk'
- '/Script/ShooterGame.StatsPanelWidget_Structure'
- '/Script/ShooterGame.StatWidget'
- '/Script/ShooterGame.StructureStatWidget'
- '/Script/ShooterGame.SupplyCrateSpawningSettings'
- '/Script/ShooterGame.TargetArea'
- '/Script/ShooterGame.TargetingInfoToolTipWidget'
- '/Script/ShooterGame.TerrainActor'
- '/Script/ShooterGame.TerrainGenerator'
- '/Script/ShooterGame.TooltipSmartLayoutWidget'
- '/Script/ShooterGame.ToolTipWidget'
- '/Script/ShooterGame.TribeManagerListButton'
- '/Script/ShooterGame.TribeMemberButtonWidget'
- '/Script/ShooterGame.TribeWarButtonWidget'
- '/Script/ShooterGame.UI_AdminMangment'
- '/Script/ShooterGame.UI_AllPlayersList'
- '/Script/ShooterGame.UI_ChangeTransponderFreqencyEntry'
- '/Script/ShooterGame.UI_ChatBox'
- '/Script/ShooterGame.UI_ChatMessage'
- '/Script/ShooterGame.UI_ClusterServersListSessions'
- '/Script/ShooterGame.UI_Cooking'
- '/Script/ShooterGame.UI_DepthOfFieldMenu'
- '/Script/ShooterGame.UI_DinoOrderGroups'
- '/Script/ShooterGame.UI_DyeItem'
- '/Script/ShooterGame.UI_EngramsMenu'
- '/Script/ShooterGame.UI_GenericConfirmationDialog'
- '/Script/ShooterGame.UI_Hairstyle'
- '/Script/ShooterGame.UI_HelpPage'
- '/Script/ShooterGame.UI_HostSession'
- '/Script/ShooterGame.UI_Hub'
- '/Script/ShooterGame.UI_HudOverlay'
- '/Script/ShooterGame.UI_Inventory'
- '/Script/ShooterGame.UI_ListCharacterData'
- '/Script/ShooterGame.UI_ListSessions'
- '/Script/ShooterGame.UI_MainMenu'
- '/Script/ShooterGame.UI_MapMarkersEntry'
- '/Script/ShooterGame.UI_MultiUse'
- '/Script/ShooterGame.UI_Notification'
- '/Script/ShooterGame.UI_OptionsMenu'
- '/Script/ShooterGame.UI_PaintingsList'
- '/Script/ShooterGame.UI_PauseMenu'
- '/Script/ShooterGame.UI_PinEntry'
- '/Script/ShooterGame.UI_ProceduralSettings'
- '/Script/ShooterGame.UI_SavePainting'
- '/Script/ShooterGame.UI_ServerBroadcastMessage'
- '/Script/ShooterGame.UI_Spawn'
- '/Script/ShooterGame.UI_SpawnPoint'
- '/Script/ShooterGame.UI_SteamInventoryStatusPopup'
- '/Script/ShooterGame.UI_Subtitles'
- '/Script/ShooterGame.UI_SurvivorProfile'
- '/Script/ShooterGame.UI_TextEntry'
- '/Script/ShooterGame.UI_TribeManager'
- '/Script/ShooterGame.UI_TribeWarEntry'
- '/Script/ShooterGame.UI_Tutorial'
- '/Script/UMG.UserWidget'
